# Generated by Django 2.2.4 on 2019-12-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_report_record_add_nickname_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='status',
            field=models.CharField(choices=[('C', '已舉報'), ('IO', '資料不齊/2016以前'), ('CO', '資料齊全/2016以前'), ('IN', '資料不齊/2016以後'), ('CN', '資料齊全/2016以後')], default='IN', max_length=2),
        ),
    ]
